contact_links:
  - name: Esri Support
    url: https://support.esri.com/en/contact-tech-support
    about: Report bugs in released versions of the SDK, and request enhancements.
  - name: Esri Community
    url: https://community.esri.com/t5/arcgis-maps-sdk-for-javascript/ct-p/arcgis-api-for-javascript
    about: Ask questions, share ideas, and collaborate with others on the ArcGIS Maps SDK for JavaScript.
