contact_links:
  - name: Esri Support
    url: https://support.esri.com/
    about: Bugs in released versions of the SDK.
  - name: ArcGIS Ideas
    url: https://community.esri.com/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&q=javascript
    about: Share your ideas with the global Esri community.    