name: Enhancement suggestion
description: Suggest an enhancement related to a new feature in the "next" release. 
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Are you in the right place?
      description: Verify the following requirements have been met before submitting your enhancement or suggestion.
      options:
        - label: My enhancement is specifically related to a NEW FEATURE in the latest "next" release. If not, please use "General enhancement:" in the issue title. For issues unrelated to the "next" version, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
          required: true
        - label: I have [checked existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicate enhancement requests. If someone has already opened an issue that is related, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.
          required: true
  - type: textarea
    id: feature
    attributes:
      label: Enhancement feature
      description: What new feature is this enhancement related to?
    validations:
      required: true
  - type: textarea
    id: category
    attributes:
      label: Enhancement category
      description: Assign the enhancement to a category
      placeholder: |
        Widgets | MapView | SceneView | Layers | Symbology | Other
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Enhancement short summary
      description: 1 - 2 sentences that summarize the enhancement or suggestion.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Enhancement description
      description: |
        A clear and concise description of the enhancement or suggestion. If applicable, add screenshots to help illustrate the issue.
    validations:
      required: true
  - type: textarea
    id: severity
    attributes:
      label: Enhancement severity
      description: How important is this enhancement and why?
      placeholder: |
        High | Medium | Low
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: SDK version (check your console)
      description: Provide the full version string from your console.
      placeholder: |
        e.g. ArcGIS Maps SDK for JavaScript 4.26-next [Date: 20221214, Revision: 144c0342]
      validations:
        required: true      
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the enhancement or suggestion.
    validations:
      required: false
